services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=amenodatabase'
      - 'POSTGRES_PASSWORD=Shikamaru123'
      - 'POSTGRES_USER=amenosignyku'
    ports:
      - '5432:5432'
    networks:
      - data-networks
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - data-networks

networks:
  data-networks:
    name: data-networks