services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spring-app.rule=Host(`api.amenosigny.com`)"
      - "traefik.http.routers.spring-app.entrypoints=websecure"
      - "traefik.http.routers.spring-app.tls=true"
      - "traefik.http.routers.spring-app.tls.certresolver=letencrypt"
      - "traefik.http.services.spring-app.loadbalancer.server.port=8081"
    networks:
      - data-networks
      - proxy

networks:
  proxy:
    name: proxy
    external: true
  data-networks:
    name: data-networks
    external: true